# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gha < Formula
  desc "Terminal UI for GitHub Actions"
  homepage "https://github.com/swibrow/github-actions-tui"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.0/github-actions-tui_0.2.0_darwin_amd64.tar.gz"
      sha256 "11071945537590c9d34b7aa8247ee269953c2c51fd86cdb73f6c0c585d4108a7"

      define_method(:install) do
        bin.install "gha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.0/github-actions-tui_0.2.0_darwin_arm64.tar.gz"
      sha256 "a3983ed2c4a294c98774be39a22335775045b4b87062d70ac9a721dd7a7db89e"

      define_method(:install) do
        bin.install "gha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.0/github-actions-tui_0.2.0_linux_amd64.tar.gz"
      sha256 "3a9b44aac45c8729d6fc6185bc6ad8f8c8516ae90df2008b7ca83fd3a36c83f2"
      define_method(:install) do
        bin.install "gha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.0/github-actions-tui_0.2.0_linux_arm64.tar.gz"
      sha256 "239cce3fe3822eb262c5c14a496bebfbec32ddf844262796c6152aa409e92deb"
      define_method(:install) do
        bin.install "gha"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gha --version")
  end
end
