# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gha < Formula
  desc "Terminal UI for GitHub Actions"
  homepage "https://github.com/swibrow/github-actions-tui"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.2/github-actions-tui_0.2.2_darwin_amd64.tar.gz"
      sha256 "fd5cd994476cce66ac3c7f61aceaecd9e6fae42987feeb3a97d92eb1567b2fe2"

      define_method(:install) do
        bin.install "gha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.2/github-actions-tui_0.2.2_darwin_arm64.tar.gz"
      sha256 "3ef7a29baeb3e445cf6b45080ad5c8f8969d15d1827389efd4535c1ecb0e1191"

      define_method(:install) do
        bin.install "gha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.2/github-actions-tui_0.2.2_linux_amd64.tar.gz"
      sha256 "1698e7f611cdd51c277b27dc41868f26bfc89e36b290e3e75498c4cb070cc0f9"
      define_method(:install) do
        bin.install "gha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.2/github-actions-tui_0.2.2_linux_arm64.tar.gz"
      sha256 "267a2b3e3199f86d085b7c5840d7c6be1785bcf0ecfc633f44c816c425735ce4"
      define_method(:install) do
        bin.install "gha"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gha --version")
  end
end
