# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gha < Formula
  desc "Terminal UI for GitHub Actions"
  homepage "https://github.com/swibrow/github-actions-tui"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.1/github-actions-tui_0.2.1_darwin_amd64.tar.gz"
      sha256 "7cd7bd811f1366971ff577e1c8f7688d851239e6e1a2ae5f4512966cc9f37c5c"

      define_method(:install) do
        bin.install "gha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.1/github-actions-tui_0.2.1_darwin_arm64.tar.gz"
      sha256 "f942359e05c04a1a07b3bc946a82b515fc233afa3dbe9eccd47e3de0d761de25"

      define_method(:install) do
        bin.install "gha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.1/github-actions-tui_0.2.1_linux_amd64.tar.gz"
      sha256 "b09895486522b5284b6dd19a589db5b2dd81eac6970df55104be390d19261980"
      define_method(:install) do
        bin.install "gha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.2.1/github-actions-tui_0.2.1_linux_arm64.tar.gz"
      sha256 "b30b512bb17cd0ada68dae56efe3a93f4225a3d385cdda7e53f85e8583558461"
      define_method(:install) do
        bin.install "gha"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gha --version")
  end
end
