# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class How < Formula
  desc "Smart terminal cheatsheet — ask a question, get a command"
  homepage "https://github.com/swibrow/how"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swibrow/how/releases/download/v1.0.1/how_1.0.1_darwin_amd64.tar.gz"
      sha256 "77d06fe8ec002c522e1c354c7957a166dbeac625ea5e4d4c43335196b63674c3"

      define_method(:install) do
        bin.install "how"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swibrow/how/releases/download/v1.0.1/how_1.0.1_darwin_arm64.tar.gz"
      sha256 "f234c1634b5e06ea0c9bdefba93f99f09d9ca311465e3db40246044e0a844163"

      define_method(:install) do
        bin.install "how"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swibrow/how/releases/download/v1.0.1/how_1.0.1_linux_amd64.tar.gz"
      sha256 "8a2b9b6d7ae9811bbdbf239f733bfaadfaee685cae2eff7cd2d1cd123fde9ac3"
      define_method(:install) do
        bin.install "how"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swibrow/how/releases/download/v1.0.1/how_1.0.1_linux_arm64.tar.gz"
      sha256 "2cfc041391f8a76240faf91e69fda994042169ede838ee9d27bfd6e1be14a416"
      define_method(:install) do
        bin.install "how"
      end
    end
  end

  test do
    system "#{bin}/how", "--help"
  end
end
