# This file was generated by GoReleaser. DO NOT EDIT.
cask "gha" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "4113b7efa691b11da3eb4d63120d4a803306e5b711e9272cd0f0f8f3c459c9c6"
      url "https://github.com/swibrow/github-actions-tui/releases/download/v#{version}/github-actions-tui_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/swibrow/github-actions-tui"
    end
    on_arm do
      sha256 "af61984d0a0f920839a047b627b0d9d50495de6ea8fbd0153d3a888f9da1d065"
      url "https://github.com/swibrow/github-actions-tui/releases/download/v#{version}/github-actions-tui_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/swibrow/github-actions-tui"
    end
  end

  name "gha"
  desc "Terminal UI for GitHub Actions"
  homepage "https://github.com/swibrow/github-actions-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gha"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gha"]
    end
  end

  # No zap stanza required

end
