# This file was generated by GoReleaser. DO NOT EDIT.
cask "how" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "e147b93835447bd2a75c1a49ea77f5f046019df88f2b776908bdce18071f5549"
      url "https://github.com/swibrow/how/releases/download/v#{version}/how_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "09dcf5d9ed3ad6fdf576a559ce59e9544e8a94c634b1523b7620115c5674c699"
      url "https://github.com/swibrow/how/releases/download/v#{version}/how_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ae90476d3c6fae7d797f2d2d7eced5c252f0684baca26f5ee9f7cc2ebe49da5"
      url "https://github.com/swibrow/how/releases/download/v#{version}/how_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5aa45f31ee18b0bdbea7c6e944177e60a714c4a478f572a45efb8da2fc43d449"
      url "https://github.com/swibrow/how/releases/download/v#{version}/how_#{version}_linux_arm64.tar.gz"
    end
  end

  name "how"
  desc "Smart terminal cheatsheet — ask a question, get a command"
  homepage "https://github.com/swibrow/how"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "how"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/how"]
    end
  end

  # No zap stanza required

end
