# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gha < Formula
  desc "Terminal UI for GitHub Actions"
  homepage "https://github.com/swibrow/github-actions-tui"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.4.0/github-actions-tui_0.4.0_darwin_amd64.tar.gz"
      sha256 "032a97081b504ddd9578244024adfd8eba6d116169d8aba9dc6175f215a3ef38"

      define_method(:install) do
        bin.install "gha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.4.0/github-actions-tui_0.4.0_darwin_arm64.tar.gz"
      sha256 "1ae9053b9312ef63d5b746bfd0fea5ee8866e9844426f33be56bd45cec38a26e"

      define_method(:install) do
        bin.install "gha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.4.0/github-actions-tui_0.4.0_linux_amd64.tar.gz"
      sha256 "4c7c1391d25c0e8362f24ccc40d673c4cd8ed6f33aa2048e5f21953079575811"
      define_method(:install) do
        bin.install "gha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swibrow/github-actions-tui/releases/download/v0.4.0/github-actions-tui_0.4.0_linux_arm64.tar.gz"
      sha256 "443d9f88f954f04eeb3ec83ca7f666e459970064a7228df25677b5f236a3744f"
      define_method(:install) do
        bin.install "gha"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gha --version")
  end
end
